USE [master]
GO

/****** Object:  Database [DB_SQL_PAIF_GAMES]    Script Date: 11/10/2025 20:46:59 ******/
CREATE DATABASE [DB_SQL_PAIF_GAMES];
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_SQL_PAIF_GAMES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET  MULTI_USER 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_SQL_PAIF_GAMES] SET  READ_WRITE 
GO


