apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: paif
spec:
  selector:
    app: payments-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api-node
  namespace: paif
spec:
  selector:
    app: payments-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort