apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: paif
spec:
  selector:
    app: users-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-node
  namespace: paif
spec:
  selector:
    app: users-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
