apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: paifgames-ns
spec:
  type: ClusterIP
  selector:
    io.kompose.service: users-api
  ports:
    - name: http
      port: 5001
      targetPort: 8080
      protocol: TCP
