apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: paif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: catalog-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: paif-shared-config }
            - secretRef: { name: paif-shared-secrets }
            - configMapRef: { name: catalog-config }
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
