apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: paifgames-ns
spec:
  type: ClusterIP
  selector:
    io.kompose.service: catalog-api
  ports:
    - name: http
      port: 5004
      targetPort: 8080
      protocol: TCP
