apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: paif
spec:
  selector:
    app: catalog-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-node
  namespace: paif
spec:
  selector:
    app: catalog-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  type: NodePort
